### ISSUE TITLE
Úprava hierarchického zobrazení hesel

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#10]
Odstranit barevné rozlišení hesel.
Prohodit pravý a prostřední sloupec, aby pořadí z leva bylo následující: úroveň, kde je vybrané heslo - informace k heslu -  jeho následníci.

**Comment by VladoKundrat** [comment]
@stanislavvelcev upravené

**Comment by motyc** [comment]
Došlo k jednomu efektu, který jsme nepředpokládali. Vše funguje skvěle pro hesla s potomky, kdy označené heslo je vždy v levém sloupci a vpravo jsou další podřazená hesla. Pokud je však heslo poslední v hierarchii, zůstane označené v pravém sloupci. Nešlo by i v takovém případě (po kliku na heslo) přesunout obsah do levého sloupce, aby to bylo konzistentní? (levý sloupec by v takovém případě zůstal prázdný, protože potomci neexistují)

Původní:
![image](https://user-images.githubusercontent.com/20186892/120618184-1ea30400-c45b-11eb-86f3-d09dae1881de.png)

Nově:
![image](https://user-images.githubusercontent.com/20186892/120618257-32e70100-c45b-11eb-8593-4abfe6cfbc80.png)
