### ISSUE TITLE
Optimalizace vyhledávání a našeptávače u dvouslovných hesel

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#11]
AIS CR prosí o optimalizací vyhledávače/našeptávače, aby našeptávač přeřadil výsledek na první pozici pod vyhledávací pole i dříve než při 100% shodě (pokud už je to zároveň jednoznačné).

**Comment by VladoKundrat** [comment]
@stanislavvelcev dostupne k otestovaniu
