### ISSUE TITLE
Zobrazení data importu datových souborů do databáze

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#12]
Datum aktualizace databáze v zápatí landing page se bude měnit v závislosti na importu datových souborů.
Import dat – databáze se naimportuje celá včetně data aktualizace. Při importu záznamu s dříve přiděleným ID dochází k jeho aktualizaci, nikoli přidělení nového ID.

**Comment by VladoKundrat** [comment]
dátum "poslední aktualizace" je už aktuálny a bude sa meniť pri importe dát.
