### ISSUE TITLE
Prvky GUI nejsou přeloženy

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#13]
Je třeba přeložit prvky GUI do obou dalších lokalizací. Průvodní text na landing page a nápovědu přeloží do obou dalších lokalizací AIS CR.

**Comment by VladoKundrat** [comment]
@stanislavvelcev upravené. Minimálne nemecký jazyk prosím skontrolujte. Preklady dlhších textov nahráme po dodání.

**Comment by stanislavvelcev** [comment]
@VladoKundrat Němčinu si projdu a zkonzultuji to ještě s dalšími němčináři.

**Comment by stanislavvelcev** [comment]
@VladoKundrat 
Dobrý den,
mám tu od mého němčináře pár návrhů na zlepšení:
Landing page
Geben Sie einen Suchbegriff --> Geben sie einen suchbegriff ein
zB Archäologische... --> z. B. archäologische
Was ist ein TEATER --> Über TEATER

Výsledky vyhledávání
ERGEBNISSE IN SCHLÜSSELNAMEN --> Ergebnisse im Stichwörterverzeichnis

**Comment by VladoKundrat** [comment]
@stanislavvelcev nahlásené vylepšenia prekladov boli zapracované

**Comment by stanislavvelcev** [comment]
@VladoKundrat  Shodli jsme se ještě na jiných názvech sloupců, čekám na potvrzené od mého němčináře a pak bych to se vložil zaráz všechno.

**Comment by stanislavvelcev** [comment]
@VladoKundrat Omlouvám se, tuto issue jsem trochu zazdil. Posílám slíbené korekce:
Term Selection - Narrower Terms
Suchbegriffe - Engere Suchbegriffe

**Comment by VladoKundrat** [comment]
@stanislavvelcev názvy stĺpcov sú upravené

**Comment by stanislavvelcev** [comment]
@VladoKundrat Prosím ještě o jednu drobnost.
Anglický text ve vyhledávacím poli změnit na: "e.g. archaeological research"

**Comment by stanislavvelcev** [comment]
@VladoKundrat 
Prosíme ještě o jednu věc - při nulovém výsledku vyhledávání v jednom nebo druhém sloupci v daném sloupci zobrazit následující informaci pro uživatele v závislosti na lokalizaci:
Žádné výsledky nebyly nalezeny
No results were found
Keine Ergebnisse werden aufgefunden

**Comment by VladoKundrat** [comment]
informačné hlášky pro užívatele sme doplnili
