### ISSUE TITLE
Přepínání lokalizací

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#14]
Přepínat jazyky lokalizací za pomocí ikon/vlaječek - buď zobrazením všech tří vlajek nebo select boxem. Řešení by mělo být viditelné a mělo by upoutat pozornost uživatele.

**Comment by VladoKundrat** [comment]
@stanislavvelcev upravené.

**Comment by petrpajdla** [comment]
Byl bych pro zvětšení pravého odsazení (německé) vlaječky od kraje stránky - zvýšilo by to viditelnost celého elementu...

**Comment by VladoKundrat** [comment]
pripravili sme nový návrh. "Vlajky" - prepínanie jazykov sme presunuli pred "nápovedu". Skúste pozrieť, jestli to je za Vás prehľadnejšie
