### ISSUE TITLE
Zprovoznit fulltextové vyhledávání 

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#15]
V současné verzi (30.05.2021) nefunguje full-textové vyhledávání - nejde vyhledávat např. podle synonym nebo textů v komentářích.

**Comment by VladoKundrat** [comment]
@stanislavvelcev dostupne k otestovaniu

**Comment by motyc** [comment]
totožný problém jako v #24 (jinak zdá se funguje, ale chtělo by více otestovat)

**Comment by stanislavvelcev** [comment]
Vyzkoušeno na cca 10 různojazyčných synonymech napříč jinými lokalizacemi. Opět ale budeme určitě klást důraz na to, aby se to otestovalo.
