### ISSUE TITLE
Zobrazování hesel ze 6. kategorie

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#17]
Opravit zobrazení hesel ze 6. kategorie, která se zobrazují mimo ni na landig page i při prohlížení tezauru.

**Comment by stanislavvelcev** [comment]
Při kontrole datových souborů jsem zjistil, že tady je chyba na naší straně, opravím.

**Comment by VladoKundrat** [comment]
ešte mierne upravíme json-y (odstránime "*", ako som včera spomínal) a nahráme novú verziu
