### ISSUE TITLE
Zobrazení citace

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#19]
Upravit zobrazení citované strany v literatuře, nyní (30.05.2021) se zobrazuje jako první údaj.  Dát na konec citace před (AIS CR preferuje) nebo za URL (pokud nepůjde jinak).

**Comment by VladoKundrat** [comment]
@stanislavvelcev upravené

**Comment by motyc** [comment]
Před stranami chybí mezera. Např. zde (http://arub.inqool.cz/cz/1-teorie-a-pristupy/archeologie).
Chybně:
> HLOŽEK, Martin, 2008. *Encyklopedie moderních metod v archeologii: Archeometrie*. Praha: Nakladatelství Libri. ISBN 978-80-7277-230-8.s. 31. Dostupné z: https://www.knihovny.cz/Record/vkol.SVK01-000882560
Správně:
> HLOŽEK, Martin, 2008. *Encyklopedie moderních metod v archeologii: Archeometrie*. Praha: Nakladatelství Libri. ISBN 978-80-7277-230-8. s. 31. Dostupné z: https://www.knihovny.cz/Record/vkol.SVK01-000882560

**Comment by VladoKundrat** [comment]
Opravené. Pred stranami v citáciách pridaná medzera
