### ISSUE TITLE
Řazení hesel v lokalizacích

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#22]
Při přepnutí do angličtiny a němčiny se hesla ve výčtu nepřeřadí podle “name” z použitého jazyka a zůstane jim pořadí z české lokalizace.

**Comment by VladoKundrat** [comment]
@stanislavvelcev dostupne k testu

**Comment by stanislavvelcev** [comment]
@VladoKundrat Stal se vedlejší efekt úspěšného zprovoznění. Hesla v páté kategorii, která mají vyplněná "date_range" a "date_accurate", se zobrazují abecedně, nikoli chronologicky.
Půjde to vyřešit?
