### ISSUE TITLE
Úprava log na landing page

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#23]
Z log nad zápatím prosíme o odstranění loga ARÚB a Akademie věd.

**Comment by VladoKundrat** [comment]
@stanislavvelcev opravené

**Comment by motyc** [comment]
@VladoKundrat zde došlo k omylu - zůstalo logo AV ČR a zmizelo logo Strategie AV21. Mělo to být obráceně.

**Comment by VladoKundrat** [comment]
Loga by už mali byť v poriadku (AV ČR sme vymenili za Strategie AV21)
