### ISSUE TITLE
Vyhledávání napříč jazyky 

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#24]
Pole na fulltextové vyhledávání nezobrazuje výsledky na dotaz psaný v jiných jazycích než je zvolená jazyková lokalizace. Tj. i v české lokalizovaci by mělo najít výsledek "sídliště" na vyhledávací dotaz "settlement".

**Comment by VladoKundrat** [comment]
@stanislavvelcev dostupne k otestovaniu

**Comment by motyc** [comment]
Funguje, ale vyskytuje se podobný problém, jako byl u dvouslovných hesel - našeptávač dá výsledky až v případě úplné shody, nikoli průběžně při psaní např.: "settlement" vs. "settle"

**Comment by VladoKundrat** [comment]
Osobne by som to nepovažoval za chybu. Cudzie výrazy sú naschvál bez našeptávača. Myslím že aj z pohľadu UX to tak bude lepšie.

Zoberte si, že by užívateľ zadal začiatok slova (napr. "set") a v návrhoch by mal mix českých, anglických, nemeckých výrazov. Pôsobilo by to možno docela metúco a pri niektorých výrazoch "náhodne".

Myslím, že nastavenie, aby sa ponúkali len výrazy z lokalizácie v ktorej ste prepnutý dáva celkom zmysel.

**Comment by motyc** [comment]
Nemyslím, že by se měly zobrazit našeptávání v angličtině (to by bylo opravdu matoucí), ale aby to našeptávalo podobně, jako když místo "sett" zadám "sett*". V tu chvíli se zobrazí hesla v jazyce zobrazení, kterým výskyt nějak odpovídá. Přidat tam tu hvězdičku nikoho moc nenapadne, když pro základní hesla se to chová jinak. Problém vidím v těch dvou variantách chování. Nebo jak to vidí @stanislavvelcev či @petrpajdla?

**Comment by stanislavvelcev** [comment]
Pokud chápu dobře @motyc Davida, tak jde o situaci, kdy mám zapnutou např. českou lokalizaci, začnu psát "settl" a nezobrazují se české výsledky dokud nemám 100% shodu, tj. až "settlement".
Jsem rozhodně pro, aby, pokud to bude možné, našeptávač ukazoval  už výsledky průběžně.
Pokud by s tím byl problém, dá se do nápovědy hint o možnosti používat zástupný znak.

**Comment by VladoKundrat** [comment]
@stanislavvelcev @motyc 

pohrali sme sa ešte s vyhľadávaním naprieč jazykmi a optimalizovali ho podľa vašich návrhov. Skúste prosím overiť, jestli je to za Vás v poriadku. Testoval som to na príklade "settl" a "swo" a systém mi ponúkal české výsledky.

**Comment by motyc** [comment]
> @stanislavvelcev @motyc
> 
> pohrali sme sa ešte s vyhľadávaním naprieč jazykmi a optimalizovali ho podľa vašich návrhov. Skúste prosím overiť, jestli je to za Vás v poriadku. Testoval som to na príklade "settl" a "swo" a systém mi ponúkal české výsledky.

Ano, za mne je to takto skvělé.

**Comment by stanislavvelcev** [comment]
Vyzkoušel jsem si cca 15 výrazů napříč jazyky a funguje to. Určitě budeme chtít po našich testerech, aby full-textové vyhledávání důkladně vyzkoušeli, ale momentálně uzavírám issue.
