### ISSUE TITLE
Layout landing page

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#25]
Prosíme o: 
1) zmenšení horního pruhu na landing page o polovinu na stejnou úroveň, jako má strana sloužící k prohlížení TEATERu
 2) výměny pořadí průvodního textu a zobrazení hlavních kategorií TEATERu na následující schéma:
okno k fulltextovému vyhledávání
"Prozkoumejte další kategorie:"
průvodní text (doplnit nadpis – „Co je to TEATER?“)

**Comment by VladoKundrat** [comment]
@stanislavvelcev upravené
