### ISSUE TITLE
Testování, issue 1, grafický layout

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#28]
Vizuál landing page vs rozkliknutí hesla
- vlaječky jazyků na landing page jsou výše, po rozkliknutí se posunou níže
- logo teateru taky nezůstane na stejném místě.

Návrh: Sjednotit na ten vizuál (tj. odsazení od stran a odshora) co je u rozkliknutí jakéhokoliv hesla i na landing page?

**Comment by VladoKundrat** [comment]
upravené, prosím o kontrolu

**Comment by stanislavvelcev** [comment]
@VladoKundrat Projdu si toto a issue vedle o víkendu, momentálně jsem zasekaný na přijímacích pohovorech.

**Comment by stanislavvelcev** [comment]
Vyzkoušeno jak při kliknutí na hlavní větve, tak při použití full-textového vyhledávání a to ve všech jazycích a vypadá to v pořádku.
