### ISSUE TITLE
Testování, issue 2, řešení PURL adresy

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#29]
Jsme pro řešení kopírovatelného a kliknutelného hyperlinku. 
Petr Pajdla navíc narazit na tento problém:
Při kliknutí na ten button navíc konzole v mozzile háže, že je tu něco špatně definovaného: Uncaught TypeError: navigator.clipboard is undefined - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type

**Comment by VladoKundrat** [comment]
odkaz sme zmenili na klasický klikateľný a kopírovací link
