### ISSUE TITLE
Testování, issue 3, nefukční našeptávač

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#30]
Mě (SV) a ještě dalším dvěma lidem, kteří to zatím napsali, nefunguje našeptávač - když do vyhledávací pole začnu psát, začne se tam točit načítací kolečko, ale neobjeví se tam nabídnuté možnosti z našeptávače musí kliknout na hledat.
Jsem si přitom jist, že v minulých verzích fungoval.

**Comment by VladoKundrat** [comment]
našeptávač opatovne funkčný. Poprosím o kontrolu.

**Comment by stanislavvelcev** [comment]
Našeptávač funguje, ozkoušeno ve všech lokalizacích.
Jenom mi to nechtělo najít heslo "antropologie" a to jak v našeptávači, tak při zobrazení výsledků po stisku enteru nebo kliknutí na lupu. Předpokládám, že je tam omezení na zobrazení výsledků (10?), nicméně 100% shoda by se tam podle mě měla dostat.

**Comment by VladoKundrat** [comment]
@stanislavvelcev 
dobrý deň, 
trocha sme sa ešte pohrali s našeptávačom a problém by už mal byť vyriešený.

**Comment by stanislavvelcev** [comment]
Vyřešeno.
