### ISSUE TITLE
Vytvořit do TEATERu PURL k jednotlivým heslům

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#7]
AIS CR navrh tento tvar.
http://teater.aiscr.cz/id/123&view=cs
http://teater.aiscr.cz/id/123&view=en
http://teater.aiscr.cz/id/123&view=de
Jedno ID záznamu, tři verze adresy. 
Vladimir Kundrát zjistí konkrétní tvar adresy (zda může být  použita výše navržená).
Zobrazení – textové zobrazení, druhý řádek hned po name.
Pokud někdo zadá adresu bez view=““, tak se jazyk hesla nastaví podle jazyku vyhledávače.

**Comment by VladoKundrat** [comment]
@stanislavvelcev  pod názov hesla bol pridaný trvalý odkaz na dané heslo

**Comment by motyc** [comment]
Bylo by prosím možné, aby byl jazyk ve struktuře PURL až na konci (http://arub.inqool.cz/cz/id/1050 -> http://arub.inqool.cz/id/1050/cz, tj. aby základní adresa byla pro všechny jazyky totožná?

Zároveň je třeba vyřešit i variantu, kdy jazyk nezadám, aby odpověď neselhala (viz výše "Pokud někdo zadá adresu bez view=““, tak se jazyk hesla nastaví podle jazyku vyhledávače.", nebo nativně nastavit češtinu - na tom již tolik nesejde).

**Comment by VladoKundrat** [comment]
Trvalé odkazy sme upravili:
- jazyk sme pridali na koniec - http://arub.inqool.cz/id/1?view=cz
- ak nebude zvolaný žiadny jazyk, tak sa použije predvolený jazyk z prehliadača. Funguje teda aj odkaz bez "view=..."

Ak súhlasíte, tak ešte urobíme jednu menšiu úpravu. Zmenil by sme "CZ" na "CS", logicky to bude dávať väčší zmysel.

**Comment by motyc** [comment]
Děkuji. Ad CS/CZ rozhodně souhlasím. Vycházel jsem z aktuálního stavu, ale také preferuji správnou verzi (CS).

**Comment by VladoKundrat** [comment]
Dobrý deň,
bola nasadená úprava s "CS"

**Comment by motyc** [comment]
V pořádku. Poslední věc zde, čistě z hlediska výpisu pURL:
1) Písmo je příliš malé a link se ztrácí. Font-size upravit na 12px.
2) Výpis se nechová jako hyperlink, ale je to nastavené jako button. Tím pádem jej nelze otevřít v novém okně, nelze jej kopírovat pomocí pravého tlačítka atd. Prosím o převedení na klasický hyperlink.
