### ISSUE TITLE
Vytvořit favikon

### ISSUE THREAD

**Issue by stanislavvelcev** [ARUP-CAS/aiscr-teater#9]
Vytvořit favikon úpravou loga bez textu.

**Comment by VladoKundrat** [comment]
@stanislavvelcev favicon pridaný

**Comment by motyc** [comment]
Nebylo by vhodnější průhledné pozadí faviconu?

**Comment by stanislavvelcev** [comment]
Bylo by možné ty čáry zesílit, než se pak následně logo zmenší na běžnou velikost Favikonu? 
V současném stavu mi přijde snadno přehlédnutelný.

**Comment by VladoKundrat** [comment]
favicon sme upravili - pokúsili sme sa ho o čosi viac zvýrazniť. Myslím, že už vyzerá docela dobre a užívateľ ho neprehľadne.

**Comment by stanislavvelcev** [comment]
@VladoKundrat 
Za mě je to v pořádku - zkusil jsem si otevřít deset záložek a favikon mi přijde dostatečně výrazný.
